"""
Module 14 — Email & Notification Service
==========================================
Handles email notifications via Gmail SMTP (SSL 465).
Supports:
  - Report Ready Notification (Student & Assigned Guide)
  - Review Submitted Alert (Student)
  - Appeal Decision Alert (Student)
  - Viva Session Completed Alert (Guide & Student)
  - Flagged Proposal Alert (Guide & HOD for High Similarity / Low Quality)
"""

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional, List

from app.config import settings

log = logging.getLogger(__name__)


def send_email(to: str, subject: str, body_html: str, body_text: Optional[str] = None) -> bool:
    """
    Sends an email using Gmail SMTP_SSL (port 465) with plain text + HTML formatting.
    Degrades gracefully — logs warning if credentials missing or network fails.
    """
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        log.warning("SMTP not configured. Skipping email to %s (Subject: %r)", to, subject)
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{settings.SMTP_FROM_NAME} <{settings.SMTP_USER}>"
    msg["To"] = to

    # Attach plain text fallback
    plain_content = body_text or "Please view this email in an HTML-compatible client."
    msg.attach(MIMEText(plain_content, "plain", "utf-8"))

    # Attach HTML body
    msg.attach(MIMEText(body_html, "html", "utf-8"))

    try:
        with smtplib.SMTP_SSL(settings.SMTP_SERVER, settings.SMTP_PORT, timeout=12.0) as server:
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.send_message(msg)
        log.info("Email successfully sent to %s (Subject: %r)", to, subject)
        return True
    except Exception as exc:
        log.error("Failed to send email to %s: %s", to, exc)
        return False


# ── HTML Email Templates ──────────────────────────────────────────────────────

def _email_container(title: str, content_html: str) -> str:
    """Standardized responsive HTML email template container."""
    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; background-color: #f4f6f9; margin: 0; padding: 20px; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }}
        .header {{ background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: #ffffff; padding: 25px; text-align: center; }}
        .header h1 {{ margin: 0; font-size: 22px; font-weight: 600; }}
        .content {{ padding: 30px; line-height: 1.6; }}
        .badge {{ display: inline-block; padding: 4px 12px; border-radius: 4px; font-size: 13px; font-weight: bold; background: #e8f4fd; color: #1e3c72; margin-bottom: 15px; }}
        .btn {{ display: inline-block; background: #2a5298; color: #ffffff !important; text-decoration: none; padding: 12px 24px; border-radius: 5px; font-weight: 600; margin-top: 20px; }}
        .footer {{ background: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #64748b; border-top: 1px solid #e2e8f0; }}
        .metric-box {{ background: #f8fafc; border-left: 4px solid #2a5298; padding: 12px; margin: 15px 0; border-radius: 0 4px 4px 0; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>AcadEval+ Platform</h1>
        </div>
        <div class="content">
            <div class="badge">{title}</div>
            {content_html}
        </div>
        <div class="footer">
            &copy; AcadEval+ Capstone Evaluation & Research Engine. Automatic system notification.
        </div>
    </div>
</body>
</html>"""


# ── Notification Helper Functions ─────────────────────────────────────────────

def notify_report_ready(student_email: str, student_name: str, project_title: str, overall_score: float, grade: str, project_id: str):
    """Notification sent to student when AI evaluation report is generated."""
    subject = f"Evaluation Report Ready: {project_title}"
    body_html = _email_container(
        title="Evaluation Complete",
        content_html=f"""
            <p>Dear <strong>{student_name}</strong>,</p>
            <p>Your capstone proposal evaluation report for <strong>"{project_title}"</strong> has been generated by the AcadEval+ AI Engine.</p>
            <div class="metric-box">
                <p style="margin:0;"><strong>Overall Score:</strong> {overall_score} / 10.0</p>
                <p style="margin:5px 0 0 0;"><strong>Grade:</strong> {grade}</p>
            </div>
            <p>You can now log in to view your complete breakdown, including your Knowledge Graph, Writing Quality, and Novelty Signals.</p>
            <a href="{settings.FRONTEND_ORIGIN}/student/reports/{project_id}" class="btn">View Full Evaluation Report</a>
        """
    )
    send_email(student_email, subject, body_html)


def notify_faculty_review_needed(guide_email: str, guide_name: str, student_name: str, project_title: str, project_id: str):
    """Notification sent to guide/reviewer when a proposal is ready for faculty review."""
    subject = f"Review Required: {project_title} ({student_name})"
    body_html = _email_container(
        title="Faculty Review Needed",
        content_html=f"""
            <p>Dear Prof. <strong>{guide_name}</strong>,</p>
            <p>A new student proposal submission by <strong>{student_name}</strong> requires your review:</p>
            <div class="metric-box">
                <p style="margin:0;"><strong>Project Title:</strong> {project_title}</p>
            </div>
            <p>The AI pre-evaluation report, Knowledge Graph, and Novelty Signals are ready for your inspection.</p>
            <a href="{settings.FRONTEND_ORIGIN}/faculty/projects/{project_id}" class="btn">Review Proposal</a>
        """
    )
    send_email(guide_email, subject, body_html)


def notify_viva_completed(guide_email: str, guide_name: str, student_name: str, project_title: str, kcs: float, grade: str, session_id: str):
    """Notification sent to faculty when a student completes their Adaptive Viva."""
    subject = f"Viva Completed: {student_name} — {project_title}"
    body_html = _email_container(
        title="Adaptive Viva Complete",
        content_html=f"""
            <p>Dear Prof. <strong>{guide_name}</strong>,</p>
            <p>Student <strong>{student_name}</strong> has completed their Intelligent Adaptive Viva Assessment for <strong>"{project_title}"</strong>.</p>
            <div class="metric-box">
                <p style="margin:0;"><strong>Knowledge Coverage Score (KCS):</strong> {kcs}%</p>
                <p style="margin:5px 0 0 0;"><strong>Viva Grade:</strong> {grade}</p>
            </div>
            <p>The complete Knowledge Gap analysis and adaptive question progression transcript are now available.</p>
            <a href="{settings.FRONTEND_ORIGIN}/faculty/viva/{session_id}/report" class="btn">View Viva Report</a>
        """
    )
    send_email(guide_email, subject, body_html)


def notify_proposal_flagged(hod_email: str, hod_name: str, project_title: str, student_name: str, flags: List[str], project_id: str):
    """Alert sent to HOD / Guide when a proposal triggers critical quality/plagiarism flags."""
    flags_list_html = "".join([f"<li>{f}</li>" for f in flags])
    subject = f"⚠️ Flagged Proposal Alert: {project_title}"
    body_html = _email_container(
        title="High Severity Alert",
        content_html=f"""
            <p>Dear <strong>{hod_name}</strong>,</p>
            <p>The proposal <strong>"{project_title}"</strong> submitted by <strong>{student_name}</strong> has triggered automated quality or similarity alerts:</p>
            <div class="metric-box" style="border-left-color: #e11d48; background: #fff1f2;">
                <ul style="margin:0; padding-left:20px; color:#be123c;">
                    {flags_list_html}
                </ul>
            </div>
            <p>Please inspect the explainable report to decide on further action.</p>
            <a href="{settings.FRONTEND_ORIGIN}/faculty/projects/{project_id}" class="btn" style="background:#e11d48;">Inspect Flagged Project</a>
        """
    )
    send_email(hod_email, subject, body_html)
